name: Build Windows

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows-static

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install build dependencies
        run: |
          choco install -y git cmake ninja llvm

      - name: Setup vcpkg (manual)
        shell: cmd
        run: |
          git clone https://github.com/microsoft/vcpkg "%RUNNER_TEMP%\vcpkg"
          "%RUNNER_TEMP%\vcpkg\bootstrap-vcpkg.bat"
          echo VCPKG_ROOT=%RUNNER_TEMP%\vcpkg>> "%GITHUB_ENV%"

      - name: Install libraries via vcpkg
        shell: powershell
        run: |
          & "$env:VCPKG_ROOT\vcpkg.exe" install `
            opus:$env:VCPKG_DEFAULT_TRIPLET `
            libvpx:$env:VCPKG_DEFAULT_TRIPLET `
            libyuv:$env:VCPKG_DEFAULT_TRIPLET `
            aom:$env:VCPKG_DEFAULT_TRIPLET

      - name: Configure environment for bindgen/clang
        shell: powershell
        run: |
          echo "LIBCLANG_PATH=C:\Program Files\LLVM\bin" >> $env:GITHUB_ENV
          echo ("BINDGEN_EXTRA_CLANG_ARGS=-I{0}" -f `
            (Join-Path $env:VCPKG_ROOT "installed\$env:VCPKG_DEFAULT_TRIPLET\include")) >> $env:GITHUB_ENV

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Get Flutter packages
        working-directory: flutter
        run: flutter pub get

      - name: Build Flutter Windows Release
        working-directory: flutter
        run: flutter build windows --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ScreenConnect-Windows
          path: flutter/build/windows/x64/runner/Release/
