name: Build Windows

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - rename-screenconnect

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install dependencies
        run: |
          choco install -y ninja cmake llvm git
          echo "Dependencies installed."

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 7ae0b9d7c8bdb8a53acdd0c0d9dc8b31482a3c06
          vcpkgTriplet: x64-windows-static
          vcpkgArguments: >
            opus libvpx libyuv

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.6"
          channel: stable

      - name: Enable Flutter Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Get Flutter dependencies
        working-directory: flutter
        run: flutter pub get

      - name: Build Flutter (Windows)
        working-directory: flutter
        run: flutter build windows --release

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: ScreenConnect-Windows
          path: flutter/build/windows/x64/runner/Release/
